### ISSUE TITLE
O que é?

### ISSUE THREAD

**Issue by veras-dan** [diogomoreira/dotfiles#1]
Estou curioso sobre esse repositório, do que se trata?

**Comment by diogomoreira** [comment]
Olá @veras-dan, por enquanto esse repositório não contem nada, mas a idéia é ter minhas configurações de zsh, git e outras ferramentas de linha de comando. Nos moldes desse repositório aqui https://github.com/thoughtbot/dotfiles

**Comment by veras-dan** [comment]
Interessante a iniciativa!!
@diogomoreira fico no aguardo então.
